* ThinkPad X280
** Notes
*** Untracked data
    Part of this configuration relies on untracked data, living outside the nix store, mannaged manually.
    Although the nix expression will evaluate successfully, the target service will not function
    correctly without the presence of this data:  
    ~/home/cmacrae/dev/nix/thinkpad/moo.ovpn~

*** Fingerprint Reader
    Not currently supported. There are efforts to reverse engineer the driver here:
    https://github.com/nmikhailov/Validity90/issues/34

    When that's working (via ~fprint~), this expression should work nicely:
    #+begin_src nix
    services.fprintd.enable = true;
    security.pam.services = {
      login.fprintAuth = true;
      su.fprintAuth = true;
      sudo.fprintAuth = true;
      "system-local-login".fprintAuth = true;
    };
    #+end_src
*** NOPASSWD sudo rules
    ~sudo~ rules can be nicely implemented using ~security.sudo.extraRules~, like so:
    #+begin_src nix
    security.sudo.extraRules = [{
      runAs = "root";
      groups = [ "wheel" ];
      commands = [{
        command = "${pkgs.systemd}/bin/systemctl * openvpn-moo";
        options = [ "NOPASSWD" ];
      }];
    }];
    #+end_src

    However, it seems there's a bug with ~extraRules~ which causes the resulting ~sudo~ expressions to be ineffective.
    Reported here: https://github.com/NixOS/nixpkgs/issues/58276
    PR raised here: https://github.com/NixOS/nixpkgs/pull/58396
    For now, ~extraConfig~ can be used to achieve the desired behaviour.
